backend:
  name: github
  repo: LukeBoults/lukeboults.github.io
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  site_domain: boulter.dev

media_folder: "public/Images"
public_folder: "/Images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail", name: "image", widget: "image", required: false }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["games", "cybersecurity"] }
      - { label: "Page Content", name: "body", widget: "markdown", required: false }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        field: { label: "Image", name: "image", widget: "image" }

  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "select", options: ["devlog", "tutorial", "announcement"] }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "passions"
    label: "Passions"
    folder: "src/content/passions"
    create: false
    extension: "json"
    format: "json"
    fields:
      - { label: "Working On", name: "working_on", widget: "string" }
      - { label: "Learning", name: "learning", widget: "string" }
      - { label: "Current Addiction", name: "current_addiction", widget: "string" }
      - { label: "Favourite Song", name: "favourite_song", widget: "string" }