backend:
  name: github
  repo: LukeBoults/lukeboults.github.io
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  site_domain: frabjous-sable-73189b.netlify.app

media_folder: "public/Images"
public_folder: "/Images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "select", options: ["devlog", "tutorial", "announcement"] }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }